Send player info
bitmovin/bitmovin-player-analytics-conviva pull request #107
Opened 2024-05-17 06:56 UTC by karpov-kir

2024-05-17 06:56 UTC, karpov-kir commented on example/index.html
> -            playerVersion: player.version,
Removed to avoid confusion

2024-05-17 12:39 UTC, dweinber requested changes
Nice addition. Please change the player name though, thanks.

2024-05-17 12:39 UTC, dweinber commented on spec/tests/ConvivaAnalytics.spec.ts
> +          frameworkName: 'bitdash',
We don't use `bitdash` publicly (anymore). Please change to `Bitmovin Player`.

```suggestion
          frameworkName: 'Bitmovin Player',
```

2024-05-17 12:39 UTC, dweinber commented on src/ts/ConvivaAnalytics.ts
> +      [Conviva.Constants.FRAMEWORK_NAME]: 'bitdash',
We don't use `bitdash` publicly (anymore). Please change to `Bitmovin Player`.

```suggestion
      [Conviva.Constants.FRAMEWORK_NAME]: 'Bitmovin Player',
```

2024-05-21 07:10 UTC, dweinber approved these changes

2024-05-21 07:33 UTC, merged