Prepare npm publishing
bitmovin/bitmovin-player-analytics-conviva pull request #26
Opened 2019-03-07 10:07 UTC by stonko1994

## Description
This PR will add required changes to enable npm publishing.

2019-03-07 11:39 UTC, protyposis reviewed
There are a few odd things with the `package.json` here:
 * This cannot be used as local package because the `main` and `types` entries point to files that do not exist, i.e. they only exist after the file has been copied to `dist`
 * The other way round, the `scripts` entries do not make sense within the `dist` folder and npm package
 * Why does `main` not point to `bitmovinplayer-analytics-conviva.js`? Why is there no `bitmovinplayer-analytics-conviva.d.ts`?

2019-03-07 12:21 UTC, stonko1994 commented
Re: 
> This cannot be used as local package because the main and types entries point to files that do not exist, i.e. they only exist after the file has been copied to dist

Where should they point then? As I understood it they should point to the `dist` (after transpiling) files. This is also the same case in the UI package

---

Re:
> The other way round, the scripts entries do not make sense within the dist folder and npm package

True

---

Re: 
> Why does main not point to bitmovinplayer-analytics-conviva.js? Why is there no bitmovinplayer-analytics-conviva.d.ts?

Why do we need the `bitmovinplayer-analytics-conviva.d.ts`? There are all types in the files included in `d.ts` files in the `dist` folder.

> Why does main not point to bitmovinplayer-analytics-conviva.js

Should it point to that? I'm not sure if there is a difference? (also taken from the UI)

2019-03-07 14:25 UTC, protyposis commented
> Where should they point then? As I understood it they should point to the dist (after transpiling) files. This is also the same case in the UI package

They should point to files that exist after running the build task.

> Why do we need the `bitmovinplayer-analytics-conviva.d.ts`? There are all types in the files included in `d.ts` files in the `dist` folder.

Because TS does automatically load types from `d.ts` files that live along `js` files. The file can simply reexport from `index.d.ts`.

Yes the compiled production build should be the default. Everybody is still free to import single files explicitly from `lib` if there is any reason for that. (The UI isn't perfect either ;) )

2019-03-07 14:26 UTC, protyposis requested changes
As outlined above.

2019-03-07 15:07 UTC, reevn reviewed
I'm just a silent watcher because this stuff interests me and I want to learn more about it. Don't wait for any real review from me 🙂

2019-03-08 10:28 UTC, protyposis approved these changes
Looking good now! (just a minor cosmetic issue)

2019-03-08 10:28 UTC, protyposis commented on webpack.common.js
> +      content: 'export * from \'./lib/index\''
Trailing `;` missing

2019-03-08 12:00 UTC, unki2aut approved these changes
LGTM :+1:

2019-03-08 12:03 UTC, merged